export const CollectibleCustom = {
  CONFUSION: Isaac.GetItemIdByName("Confusion"),
  BLINK: Isaac.GetItemIdByName("Blink"),
  DOOM_DESIRE: Isaac.GetItemIdByName("Doom Desire"),
  FRUSTRATION: Isaac.GetItemIdByName("Frustration"),
  HEART_FIN: Isaac.GetItemIdByName("Heart Fin"),
  LATIAS_MASK: Isaac.GetItemIdByName("Latias Mask"),
  PSYCHIC: Isaac.GetItemIdByName("Psychic"),
  WITCHS_BRAIDS: Isaac.GetItemIdByName("Witch's Braids"),
  FUTURE_SIGHT: Isaac.GetItemIdByName("Future Sight"),
  TAPUS_FIN: Isaac.GetItemIdByName("Tapu's Fin"),
  TRIPLE_AXEL: Isaac.GetItemIdByName("Triple Axel"),
  WISH: Isaac.GetItemIdByName("Wish"),
  MOON_BABY: Isaac.GetItemIdByName("Moon Baby"),
  HYPNOS_PENDULUM: Isaac.GetItemIdByName("Hypno's Pendulum"),
  DREAM_EATER: Isaac.GetItemIdByName("Dream Eater"),
  WISHMAKER_PENDANT: Isaac.GetItemIdByName("Wishmaker Pendant"),
  PSIONIC_PERSUASION: Isaac.GetItemIdByName("Psionic Persuasion"),
  TARNISHED_LOCKET: Isaac.GetItemIdByName("Tarnished Locket   "),
  TARNISHED_LOCKET_2: Isaac.GetItemIdByName("Tarnished Locket"),
  AIR_BALLOON: Isaac.GetItemIdByName("Air Balloon"),
  ASTRAS_RESOLVE: Isaac.GetItemIdByName("Astra's Resolve"),
  CHOICE_SCARF: Isaac.GetItemIdByName("Choice Scarf"),
  CLEANSE_TAG: Isaac.GetItemIdByName("Cleanse Tag"),
  LIFE_ORB: Isaac.GetItemIdByName("Life Orb"),
  SOOTHE_BELL: Isaac.GetItemIdByName("Soothe Bell")
} as const;
